/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Gerenciamento de Treinos API
 * API para o Gerenciamento de Treinos
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetAdminStats200UsersByPlan = { [key: string]: number };

export type GetAdminStats200 = {
  totalUsers: number;
  usersByPlan: GetAdminStats200UsersByPlan;
  activeSubscriptions: number;
  newUsersThisMonth: number;
};

export type GetAdminStats401 = {
  error: string;
  code: string;
};

export type GetAdminStats403 = {
  error: string;
  code: string;
};

export type GetAdminStats500 = {
  error: string;
  code: string;
};

export type ListAdminUsersParams = {
  search?: string;
  plan?: string;
  status?: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type ListAdminUsers200UsersItemPlan =
  (typeof ListAdminUsers200UsersItemPlan)[keyof typeof ListAdminUsers200UsersItemPlan];

export const ListAdminUsers200UsersItemPlan = {
  FREE: "FREE",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
} as const;

/**
 * @nullable
 */
export type ListAdminUsers200UsersItemSubscriptionStatus =
  | (typeof ListAdminUsers200UsersItemSubscriptionStatus)[keyof typeof ListAdminUsers200UsersItemSubscriptionStatus]
  | null;

export const ListAdminUsers200UsersItemSubscriptionStatus = {
  ACTIVE: "ACTIVE",
  CANCELED: "CANCELED",
  INCOMPLETE: "INCOMPLETE",
  PAST_DUE: "PAST_DUE",
} as const;

export type ListAdminUsers200UsersItem = {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  image: string | null;
  plan: ListAdminUsers200UsersItemPlan;
  /** @nullable */
  subscriptionStatus: ListAdminUsers200UsersItemSubscriptionStatus;
  role: string;
  banned: boolean;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
};

export type ListAdminUsers200 = {
  users: ListAdminUsers200UsersItem[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
};

export type ListAdminUsers401 = {
  error: string;
  code: string;
};

export type ListAdminUsers403 = {
  error: string;
  code: string;
};

export type ListAdminUsers500 = {
  error: string;
  code: string;
};

export type GetAdminUserDetail200Plan =
  (typeof GetAdminUserDetail200Plan)[keyof typeof GetAdminUserDetail200Plan];

export const GetAdminUserDetail200Plan = {
  FREE: "FREE",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
} as const;

/**
 * @nullable
 */
export type GetAdminUserDetail200SubscriptionStatus =
  | (typeof GetAdminUserDetail200SubscriptionStatus)[keyof typeof GetAdminUserDetail200SubscriptionStatus]
  | null;

export const GetAdminUserDetail200SubscriptionStatus = {
  ACTIVE: "ACTIVE",
  CANCELED: "CANCELED",
  INCOMPLETE: "INCOMPLETE",
  PAST_DUE: "PAST_DUE",
} as const;

export type GetAdminUserDetail200 = {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  image: string | null;
  plan: GetAdminUserDetail200Plan;
  /** @nullable */
  subscriptionStatus: GetAdminUserDetail200SubscriptionStatus;
  /** @nullable */
  stripeCustomerId: string | null;
  role: string;
  banned: boolean;
  /** @nullable */
  banReason: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  banExpires: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  /** @nullable */
  weightInGrams: number | null;
  /** @nullable */
  heightInCentimeters: number | null;
  /** @nullable */
  age: number | null;
  /** @nullable */
  bodyFatPercentage: number | null;
  workoutPlansCount: number;
  sessionsCount: number;
};

export type GetAdminUserDetail401 = {
  error: string;
  code: string;
};

export type GetAdminUserDetail403 = {
  error: string;
  code: string;
};

export type GetAdminUserDetail404 = {
  error: string;
  code: string;
};

export type GetAdminUserDetail500 = {
  error: string;
  code: string;
};

export type BanAdminUserBody = {
  banReason?: string;
  banExpiresIn?: number;
};

export type BanAdminUser200 = {
  message: string;
};

export type BanAdminUser401 = {
  error: string;
  code: string;
};

export type BanAdminUser403 = {
  error: string;
  code: string;
};

export type BanAdminUser500 = {
  error: string;
  code: string;
};

export type UnbanAdminUser200 = {
  message: string;
};

export type UnbanAdminUser401 = {
  error: string;
  code: string;
};

export type UnbanAdminUser403 = {
  error: string;
  code: string;
};

export type UnbanAdminUser500 = {
  error: string;
  code: string;
};

export type GetAdminUserWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetAdminUserWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetAdminUserWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const GetAdminUserWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetAdminUserWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  /** @nullable */
  weightInKg: number | null;
  /** @nullable */
  gifUrl: string | null;
};

export type GetAdminUserWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetAdminUserWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  exercises: GetAdminUserWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type GetAdminUserWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  workoutDays: GetAdminUserWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetAdminUserWorkoutPlans401 = {
  error: string;
  code: string;
};

export type GetAdminUserWorkoutPlans403 = {
  error: string;
  code: string;
};

export type GetAdminUserWorkoutPlans404 = {
  error: string;
  code: string;
};

export type GetAdminUserWorkoutPlans500 = {
  error: string;
  code: string;
};

export type UpdateAdminWorkoutExerciseBody = {
  /** @minLength 1 */
  name?: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  sets?: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  reps?: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  restTimeInSeconds?: number;
  /**
   * @minimum 0
   * @nullable
   */
  weightInKg?: number | null;
  /** @nullable */
  gifUrl?: string | null;
};

export type UpdateAdminWorkoutExercise200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  /** @nullable */
  weightInKg: number | null;
  /** @nullable */
  gifUrl: string | null;
};

export type UpdateAdminWorkoutExercise401 = {
  error: string;
  code: string;
};

export type UpdateAdminWorkoutExercise403 = {
  error: string;
  code: string;
};

export type UpdateAdminWorkoutExercise404 = {
  error: string;
  code: string;
};

export type UpdateAdminWorkoutExercise500 = {
  error: string;
  code: string;
};

export type DeleteAdminExercise200 = {
  message: string;
};

export type DeleteAdminExercise401 = {
  error: string;
  code: string;
};

export type DeleteAdminExercise403 = {
  error: string;
  code: string;
};

export type DeleteAdminExercise404 = {
  error: string;
  code: string;
};

export type DeleteAdminExercise500 = {
  error: string;
  code: string;
};

export type AddAdminExerciseBody = {
  /** @minLength 1 */
  name: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  sets: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  reps: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  restTimeInSeconds: number;
  /**
   * @minimum 0
   * @nullable
   */
  weightInKg?: number | null;
  /** @nullable */
  gifUrl?: string | null;
};

export type AddAdminExercise201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  /** @nullable */
  weightInKg: number | null;
  /** @nullable */
  gifUrl: string | null;
};

export type AddAdminExercise401 = {
  error: string;
  code: string;
};

export type AddAdminExercise403 = {
  error: string;
  code: string;
};

export type AddAdminExercise404 = {
  error: string;
  code: string;
};

export type AddAdminExercise500 = {
  error: string;
  code: string;
};

export type SearchExerciseDbParams = {
  /**
   * @minLength 1
   */
  q: string;
};

export type SearchExerciseDb200Item = {
  name: string;
  gifUrl: string;
  bodyParts: string[];
  targetMuscles: string[];
};

export type SearchExerciseDb401 = {
  error: string;
  code: string;
};

export type SearchExerciseDb403 = {
  error: string;
  code: string;
};

export type SearchExerciseDb500 = {
  error: string;
  code: string;
};

export type GetAdminStripeLogsParams = {
  type?: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  startDate?: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  endDate?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  startingAfter?: string;
};

export type GetAdminStripeLogs200EventsItemData = { [key: string]: unknown };

export type GetAdminStripeLogs200EventsItem = {
  id: string;
  type: string;
  created: number;
  data: GetAdminStripeLogs200EventsItemData;
};

export type GetAdminStripeLogs200 = {
  events: GetAdminStripeLogs200EventsItem[];
  hasMore: boolean;
};

export type GetAdminStripeLogs401 = {
  error: string;
  code: string;
};

export type GetAdminStripeLogs403 = {
  error: string;
  code: string;
};

export type GetAdminStripeLogs500 = {
  error: string;
  code: string;
};

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  coverImageUrl?: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  coverImageUrl?: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  /** @nullable */
  weightInKg: number | null;
  /** @nullable */
  gifUrl: string | null;
};

export type GetWorkoutDay200SessionsItemSessionExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  exerciseId: string;
  isCompleted: boolean;
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  startedAt?: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  completedAt?: string | null;
  sessionExercises: GetWorkoutDay200SessionsItemSessionExercisesItem[];
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDay200WeekDay;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  completedAt: string;
  startedAt: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateSessionExerciseBody = {
  isCompleted: boolean;
};

export type UpdateSessionExercise200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  exerciseId: string;
  isCompleted: boolean;
};

export type UpdateSessionExercise401 = {
  error: string;
  code: string;
};

export type UpdateSessionExercise404 = {
  error: string;
  code: string;
};

export type UpdateSessionExercise500 = {
  error: string;
  code: string;
};

export type UpdateExerciseWeightBody = {
  /**
   * @minimum 0
   * @nullable
   */
  weightInKg: number | null;
};

export type UpdateExerciseWeight200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  weightInKg: number | null;
};

export type UpdateExerciseWeight401 = {
  error: string;
  code: string;
};

export type UpdateExerciseWeight404 = {
  error: string;
  code: string;
};

export type UpdateExerciseWeight500 = {
  error: string;
  code: string;
};

export type GetHomeParams = {
  timezone?: string;
};

/**
 * @nullable
 */
export type GetHome200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | 00000000-0000-0000-0000-000000000000 | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12} | ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay:
    | "MONDAY"
    | "TUESDAY"
    | "WEDNESDAY"
    | "THURSDAY"
    | "FRIDAY"
    | "SATURDAY"
    | "SUNDAY";
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
} | null;

export type GetHome200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHome200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  /** @nullable */
  todayWorkoutDay: GetHome200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHome200ConsistencyByDay;
};

export type GetHome401 = {
  error: string;
  code: string;
};

export type GetHome404 = {
  error: string;
  code: string;
};

export type GetHome500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
  timezone?: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  /** @nullable */
  bodyFatPercentage: number | null;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @maximum 9007199254740991 */
  weightInGrams: number;
  /** @maximum 9007199254740991 */
  heightInCentimeters: number;
  /** @maximum 9007199254740991 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  bodyFatPercentage?: number | null;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  /** @nullable */
  bodyFatPercentage: number | null;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type PostCreateCheckoutSessionBodyPlan =
  (typeof PostCreateCheckoutSessionBodyPlan)[keyof typeof PostCreateCheckoutSessionBodyPlan];

export const PostCreateCheckoutSessionBodyPlan = {
  MONTHLY: "MONTHLY",
  YEARLY: "YEARLY",
} as const;

export type PostCreateCheckoutSessionBody = {
  plan: PostCreateCheckoutSessionBodyPlan;
};

export type PostCreateCheckoutSession200 = {
  checkoutUrl: string;
};

export type PostCreateCheckoutSession401 = {
  error: string;
  code: string;
};

export type PostCreateCheckoutSession500 = {
  error: string;
  code: string;
};

export type GetSubscription200Plan =
  (typeof GetSubscription200Plan)[keyof typeof GetSubscription200Plan];

export const GetSubscription200Plan = {
  FREE: "FREE",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
} as const;

/**
 * @nullable
 */
export type GetSubscription200SubscriptionStatus =
  | (typeof GetSubscription200SubscriptionStatus)[keyof typeof GetSubscription200SubscriptionStatus]
  | null;

export const GetSubscription200SubscriptionStatus = {
  ACTIVE: "ACTIVE",
  CANCELED: "CANCELED",
  INCOMPLETE: "INCOMPLETE",
  PAST_DUE: "PAST_DUE",
} as const;

export type GetSubscription200 = {
  plan: GetSubscription200Plan;
  /** @nullable */
  subscriptionStatus: GetSubscription200SubscriptionStatus;
  /** @nullable */
  stripeCustomerId: string | null;
  /** @nullable */
  subscriptionId: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
   */
  currentPeriodEnd: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  trialEndsAt: string;
  isTrialActive: boolean;
  hasAccess: boolean;
};

export type GetSubscription401 = {
  error: string;
  code: string;
};

export type GetSubscription404 = {
  error: string;
  code: string;
};

export type GetSubscription500 = {
  error: string;
  code: string;
};

export type PostCancelSubscription200 = {
  message: string;
};

export type PostCancelSubscription400 = {
  error: string;
  code: string;
};

export type PostCancelSubscription401 = {
  error: string;
  code: string;
};

export type PostCancelSubscription404 = {
  error: string;
  code: string;
};

export type PostCancelSubscription500 = {
  error: string;
  code: string;
};

export type PostChangePlanBodyPlan =
  (typeof PostChangePlanBodyPlan)[keyof typeof PostChangePlanBodyPlan];

export const PostChangePlanBodyPlan = {
  MONTHLY: "MONTHLY",
  YEARLY: "YEARLY",
} as const;

export type PostChangePlanBody = {
  plan: PostChangePlanBodyPlan;
};

export type PostChangePlan200Plan =
  (typeof PostChangePlan200Plan)[keyof typeof PostChangePlan200Plan];

export const PostChangePlan200Plan = {
  FREE: "FREE",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
} as const;

export type PostChangePlan200 = {
  message: string;
  plan: PostChangePlan200Plan;
};

export type PostChangePlan400 = {
  error: string;
  code: string;
};

export type PostChangePlan401 = {
  error: string;
  code: string;
};

export type PostChangePlan404 = {
  error: string;
  code: string;
};

export type PostChangePlan500 = {
  error: string;
  code: string;
};

/**
 * @summary Get admin dashboard statistics
 */
export type getAdminStatsResponse200 = {
  data: GetAdminStats200;
  status: 200;
};

export type getAdminStatsResponse401 = {
  data: GetAdminStats401;
  status: 401;
};

export type getAdminStatsResponse403 = {
  data: GetAdminStats403;
  status: 403;
};

export type getAdminStatsResponse500 = {
  data: GetAdminStats500;
  status: 500;
};

export type getAdminStatsResponseSuccess = getAdminStatsResponse200 & {
  headers: Headers;
};
export type getAdminStatsResponseError = (
  | getAdminStatsResponse401
  | getAdminStatsResponse403
  | getAdminStatsResponse500
) & {
  headers: Headers;
};

export type getAdminStatsResponse =
  | getAdminStatsResponseSuccess
  | getAdminStatsResponseError;

export const getGetAdminStatsUrl = () => {
  return `/admin/stats`;
};

export const getAdminStats = async (
  options?: RequestInit,
): Promise<getAdminStatsResponse> => {
  return customFetch<getAdminStatsResponse>(getGetAdminStatsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List users with pagination and filters
 */
export type listAdminUsersResponse200 = {
  data: ListAdminUsers200;
  status: 200;
};

export type listAdminUsersResponse401 = {
  data: ListAdminUsers401;
  status: 401;
};

export type listAdminUsersResponse403 = {
  data: ListAdminUsers403;
  status: 403;
};

export type listAdminUsersResponse500 = {
  data: ListAdminUsers500;
  status: 500;
};

export type listAdminUsersResponseSuccess = listAdminUsersResponse200 & {
  headers: Headers;
};
export type listAdminUsersResponseError = (
  | listAdminUsersResponse401
  | listAdminUsersResponse403
  | listAdminUsersResponse500
) & {
  headers: Headers;
};

export type listAdminUsersResponse =
  | listAdminUsersResponseSuccess
  | listAdminUsersResponseError;

export const getListAdminUsersUrl = (params?: ListAdminUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/admin/users?${stringifiedParams}`
    : `/admin/users`;
};

export const listAdminUsers = async (
  params?: ListAdminUsersParams,
  options?: RequestInit,
): Promise<listAdminUsersResponse> => {
  return customFetch<listAdminUsersResponse>(getListAdminUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get detailed user information
 */
export type getAdminUserDetailResponse200 = {
  data: GetAdminUserDetail200;
  status: 200;
};

export type getAdminUserDetailResponse401 = {
  data: GetAdminUserDetail401;
  status: 401;
};

export type getAdminUserDetailResponse403 = {
  data: GetAdminUserDetail403;
  status: 403;
};

export type getAdminUserDetailResponse404 = {
  data: GetAdminUserDetail404;
  status: 404;
};

export type getAdminUserDetailResponse500 = {
  data: GetAdminUserDetail500;
  status: 500;
};

export type getAdminUserDetailResponseSuccess =
  getAdminUserDetailResponse200 & {
    headers: Headers;
  };
export type getAdminUserDetailResponseError = (
  | getAdminUserDetailResponse401
  | getAdminUserDetailResponse403
  | getAdminUserDetailResponse404
  | getAdminUserDetailResponse500
) & {
  headers: Headers;
};

export type getAdminUserDetailResponse =
  | getAdminUserDetailResponseSuccess
  | getAdminUserDetailResponseError;

export const getGetAdminUserDetailUrl = (userId: string) => {
  return `/admin/users/${userId}`;
};

export const getAdminUserDetail = async (
  userId: string,
  options?: RequestInit,
): Promise<getAdminUserDetailResponse> => {
  return customFetch<getAdminUserDetailResponse>(
    getGetAdminUserDetailUrl(userId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Ban a user
 */
export type banAdminUserResponse200 = {
  data: BanAdminUser200;
  status: 200;
};

export type banAdminUserResponse401 = {
  data: BanAdminUser401;
  status: 401;
};

export type banAdminUserResponse403 = {
  data: BanAdminUser403;
  status: 403;
};

export type banAdminUserResponse500 = {
  data: BanAdminUser500;
  status: 500;
};

export type banAdminUserResponseSuccess = banAdminUserResponse200 & {
  headers: Headers;
};
export type banAdminUserResponseError = (
  | banAdminUserResponse401
  | banAdminUserResponse403
  | banAdminUserResponse500
) & {
  headers: Headers;
};

export type banAdminUserResponse =
  | banAdminUserResponseSuccess
  | banAdminUserResponseError;

export const getBanAdminUserUrl = (userId: string) => {
  return `/admin/users/${userId}/ban`;
};

export const banAdminUser = async (
  userId: string,
  banAdminUserBody: BanAdminUserBody,
  options?: RequestInit,
): Promise<banAdminUserResponse> => {
  return customFetch<banAdminUserResponse>(getBanAdminUserUrl(userId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(banAdminUserBody),
  });
};

/**
 * @summary Unban a user
 */
export type unbanAdminUserResponse200 = {
  data: UnbanAdminUser200;
  status: 200;
};

export type unbanAdminUserResponse401 = {
  data: UnbanAdminUser401;
  status: 401;
};

export type unbanAdminUserResponse403 = {
  data: UnbanAdminUser403;
  status: 403;
};

export type unbanAdminUserResponse500 = {
  data: UnbanAdminUser500;
  status: 500;
};

export type unbanAdminUserResponseSuccess = unbanAdminUserResponse200 & {
  headers: Headers;
};
export type unbanAdminUserResponseError = (
  | unbanAdminUserResponse401
  | unbanAdminUserResponse403
  | unbanAdminUserResponse500
) & {
  headers: Headers;
};

export type unbanAdminUserResponse =
  | unbanAdminUserResponseSuccess
  | unbanAdminUserResponseError;

export const getUnbanAdminUserUrl = (userId: string) => {
  return `/admin/users/${userId}/unban`;
};

export const unbanAdminUser = async (
  userId: string,
  options?: RequestInit,
): Promise<unbanAdminUserResponse> => {
  return customFetch<unbanAdminUserResponse>(getUnbanAdminUserUrl(userId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary List workout plans for a specific user
 */
export type getAdminUserWorkoutPlansResponse200 = {
  data: GetAdminUserWorkoutPlans200Item[];
  status: 200;
};

export type getAdminUserWorkoutPlansResponse401 = {
  data: GetAdminUserWorkoutPlans401;
  status: 401;
};

export type getAdminUserWorkoutPlansResponse403 = {
  data: GetAdminUserWorkoutPlans403;
  status: 403;
};

export type getAdminUserWorkoutPlansResponse404 = {
  data: GetAdminUserWorkoutPlans404;
  status: 404;
};

export type getAdminUserWorkoutPlansResponse500 = {
  data: GetAdminUserWorkoutPlans500;
  status: 500;
};

export type getAdminUserWorkoutPlansResponseSuccess =
  getAdminUserWorkoutPlansResponse200 & {
    headers: Headers;
  };
export type getAdminUserWorkoutPlansResponseError = (
  | getAdminUserWorkoutPlansResponse401
  | getAdminUserWorkoutPlansResponse403
  | getAdminUserWorkoutPlansResponse404
  | getAdminUserWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type getAdminUserWorkoutPlansResponse =
  | getAdminUserWorkoutPlansResponseSuccess
  | getAdminUserWorkoutPlansResponseError;

export const getGetAdminUserWorkoutPlansUrl = (userId: string) => {
  return `/admin/users/${userId}/workout-plans`;
};

export const getAdminUserWorkoutPlans = async (
  userId: string,
  options?: RequestInit,
): Promise<getAdminUserWorkoutPlansResponse> => {
  return customFetch<getAdminUserWorkoutPlansResponse>(
    getGetAdminUserWorkoutPlansUrl(userId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update a workout exercise for a specific user
 */
export type updateAdminWorkoutExerciseResponse200 = {
  data: UpdateAdminWorkoutExercise200;
  status: 200;
};

export type updateAdminWorkoutExerciseResponse401 = {
  data: UpdateAdminWorkoutExercise401;
  status: 401;
};

export type updateAdminWorkoutExerciseResponse403 = {
  data: UpdateAdminWorkoutExercise403;
  status: 403;
};

export type updateAdminWorkoutExerciseResponse404 = {
  data: UpdateAdminWorkoutExercise404;
  status: 404;
};

export type updateAdminWorkoutExerciseResponse500 = {
  data: UpdateAdminWorkoutExercise500;
  status: 500;
};

export type updateAdminWorkoutExerciseResponseSuccess =
  updateAdminWorkoutExerciseResponse200 & {
    headers: Headers;
  };
export type updateAdminWorkoutExerciseResponseError = (
  | updateAdminWorkoutExerciseResponse401
  | updateAdminWorkoutExerciseResponse403
  | updateAdminWorkoutExerciseResponse404
  | updateAdminWorkoutExerciseResponse500
) & {
  headers: Headers;
};

export type updateAdminWorkoutExerciseResponse =
  | updateAdminWorkoutExerciseResponseSuccess
  | updateAdminWorkoutExerciseResponseError;

export const getUpdateAdminWorkoutExerciseUrl = (
  userId: string,
  exerciseId: string,
) => {
  return `/admin/users/${userId}/exercises/${exerciseId}`;
};

export const updateAdminWorkoutExercise = async (
  userId: string,
  exerciseId: string,
  updateAdminWorkoutExerciseBody: UpdateAdminWorkoutExerciseBody,
  options?: RequestInit,
): Promise<updateAdminWorkoutExerciseResponse> => {
  return customFetch<updateAdminWorkoutExerciseResponse>(
    getUpdateAdminWorkoutExerciseUrl(userId, exerciseId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateAdminWorkoutExerciseBody),
    },
  );
};

/**
 * @summary Delete a workout exercise for a specific user
 */
export type deleteAdminExerciseResponse200 = {
  data: DeleteAdminExercise200;
  status: 200;
};

export type deleteAdminExerciseResponse401 = {
  data: DeleteAdminExercise401;
  status: 401;
};

export type deleteAdminExerciseResponse403 = {
  data: DeleteAdminExercise403;
  status: 403;
};

export type deleteAdminExerciseResponse404 = {
  data: DeleteAdminExercise404;
  status: 404;
};

export type deleteAdminExerciseResponse500 = {
  data: DeleteAdminExercise500;
  status: 500;
};

export type deleteAdminExerciseResponseSuccess =
  deleteAdminExerciseResponse200 & {
    headers: Headers;
  };
export type deleteAdminExerciseResponseError = (
  | deleteAdminExerciseResponse401
  | deleteAdminExerciseResponse403
  | deleteAdminExerciseResponse404
  | deleteAdminExerciseResponse500
) & {
  headers: Headers;
};

export type deleteAdminExerciseResponse =
  | deleteAdminExerciseResponseSuccess
  | deleteAdminExerciseResponseError;

export const getDeleteAdminExerciseUrl = (
  userId: string,
  exerciseId: string,
) => {
  return `/admin/users/${userId}/exercises/${exerciseId}`;
};

export const deleteAdminExercise = async (
  userId: string,
  exerciseId: string,
  options?: RequestInit,
): Promise<deleteAdminExerciseResponse> => {
  return customFetch<deleteAdminExerciseResponse>(
    getDeleteAdminExerciseUrl(userId, exerciseId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Add an exercise to a workout day for a specific user
 */
export type addAdminExerciseResponse201 = {
  data: AddAdminExercise201;
  status: 201;
};

export type addAdminExerciseResponse401 = {
  data: AddAdminExercise401;
  status: 401;
};

export type addAdminExerciseResponse403 = {
  data: AddAdminExercise403;
  status: 403;
};

export type addAdminExerciseResponse404 = {
  data: AddAdminExercise404;
  status: 404;
};

export type addAdminExerciseResponse500 = {
  data: AddAdminExercise500;
  status: 500;
};

export type addAdminExerciseResponseSuccess = addAdminExerciseResponse201 & {
  headers: Headers;
};
export type addAdminExerciseResponseError = (
  | addAdminExerciseResponse401
  | addAdminExerciseResponse403
  | addAdminExerciseResponse404
  | addAdminExerciseResponse500
) & {
  headers: Headers;
};

export type addAdminExerciseResponse =
  | addAdminExerciseResponseSuccess
  | addAdminExerciseResponseError;

export const getAddAdminExerciseUrl = (
  userId: string,
  workoutDayId: string,
) => {
  return `/admin/users/${userId}/days/${workoutDayId}/exercises`;
};

export const addAdminExercise = async (
  userId: string,
  workoutDayId: string,
  addAdminExerciseBody: AddAdminExerciseBody,
  options?: RequestInit,
): Promise<addAdminExerciseResponse> => {
  return customFetch<addAdminExerciseResponse>(
    getAddAdminExerciseUrl(userId, workoutDayId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(addAdminExerciseBody),
    },
  );
};

/**
 * @summary Search exercises from ExerciseDB
 */
export type searchExerciseDbResponse200 = {
  data: SearchExerciseDb200Item[];
  status: 200;
};

export type searchExerciseDbResponse401 = {
  data: SearchExerciseDb401;
  status: 401;
};

export type searchExerciseDbResponse403 = {
  data: SearchExerciseDb403;
  status: 403;
};

export type searchExerciseDbResponse500 = {
  data: SearchExerciseDb500;
  status: 500;
};

export type searchExerciseDbResponseSuccess = searchExerciseDbResponse200 & {
  headers: Headers;
};
export type searchExerciseDbResponseError = (
  | searchExerciseDbResponse401
  | searchExerciseDbResponse403
  | searchExerciseDbResponse500
) & {
  headers: Headers;
};

export type searchExerciseDbResponse =
  | searchExerciseDbResponseSuccess
  | searchExerciseDbResponseError;

export const getSearchExerciseDbUrl = (params: SearchExerciseDbParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/admin/exercises/search?${stringifiedParams}`
    : `/admin/exercises/search`;
};

export const searchExerciseDb = async (
  params: SearchExerciseDbParams,
  options?: RequestInit,
): Promise<searchExerciseDbResponse> => {
  return customFetch<searchExerciseDbResponse>(getSearchExerciseDbUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get Stripe event logs
 */
export type getAdminStripeLogsResponse200 = {
  data: GetAdminStripeLogs200;
  status: 200;
};

export type getAdminStripeLogsResponse401 = {
  data: GetAdminStripeLogs401;
  status: 401;
};

export type getAdminStripeLogsResponse403 = {
  data: GetAdminStripeLogs403;
  status: 403;
};

export type getAdminStripeLogsResponse500 = {
  data: GetAdminStripeLogs500;
  status: 500;
};

export type getAdminStripeLogsResponseSuccess =
  getAdminStripeLogsResponse200 & {
    headers: Headers;
  };
export type getAdminStripeLogsResponseError = (
  | getAdminStripeLogsResponse401
  | getAdminStripeLogsResponse403
  | getAdminStripeLogsResponse500
) & {
  headers: Headers;
};

export type getAdminStripeLogsResponse =
  | getAdminStripeLogsResponseSuccess
  | getAdminStripeLogsResponseError;

export const getGetAdminStripeLogsUrl = (params?: GetAdminStripeLogsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/admin/stripe-logs?${stringifiedParams}`
    : `/admin/stripe-logs`;
};

export const getAdminStripeLogs = async (
  params?: GetAdminStripeLogsParams,
  options?: RequestInit,
): Promise<getAdminStripeLogsResponse> => {
  return customFetch<getAdminStripeLogsResponse>(
    getGetAdminStripeLogsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/?${stringifiedParams}` : `/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get a workout plan by ID
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (id: string) => {
  return `/${id}`;
};

export const getWorkoutPlan = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get a workout day by ID
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a workout session for a day
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200;
  status: 200;
};

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401;
  status: 401;
};

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404;
  status: 404;
};

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500;
  status: 500;
};

export type updateWorkoutSessionResponseSuccess =
  updateWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type updateWorkoutSessionResponseError = (
  | updateWorkoutSessionResponse401
  | updateWorkoutSessionResponse404
  | updateWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse =
  | updateWorkoutSessionResponseSuccess
  | updateWorkoutSessionResponseError;

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<updateWorkoutSessionResponse>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Update a session exercise (check/uncheck)
 */
export type updateSessionExerciseResponse200 = {
  data: UpdateSessionExercise200;
  status: 200;
};

export type updateSessionExerciseResponse401 = {
  data: UpdateSessionExercise401;
  status: 401;
};

export type updateSessionExerciseResponse404 = {
  data: UpdateSessionExercise404;
  status: 404;
};

export type updateSessionExerciseResponse500 = {
  data: UpdateSessionExercise500;
  status: 500;
};

export type updateSessionExerciseResponseSuccess =
  updateSessionExerciseResponse200 & {
    headers: Headers;
  };
export type updateSessionExerciseResponseError = (
  | updateSessionExerciseResponse401
  | updateSessionExerciseResponse404
  | updateSessionExerciseResponse500
) & {
  headers: Headers;
};

export type updateSessionExerciseResponse =
  | updateSessionExerciseResponseSuccess
  | updateSessionExerciseResponseError;

export const getUpdateSessionExerciseUrl = (
  workoutPlanId: string,
  sessionId: string,
  sessionExerciseId: string,
) => {
  return `/${workoutPlanId}/sessions/${sessionId}/exercises/${sessionExerciseId}`;
};

export const updateSessionExercise = async (
  workoutPlanId: string,
  sessionId: string,
  sessionExerciseId: string,
  updateSessionExerciseBody: UpdateSessionExerciseBody,
  options?: RequestInit,
): Promise<updateSessionExerciseResponse> => {
  return customFetch<updateSessionExerciseResponse>(
    getUpdateSessionExerciseUrl(workoutPlanId, sessionId, sessionExerciseId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateSessionExerciseBody),
    },
  );
};

/**
 * @summary Update exercise weight
 */
export type updateExerciseWeightResponse200 = {
  data: UpdateExerciseWeight200;
  status: 200;
};

export type updateExerciseWeightResponse401 = {
  data: UpdateExerciseWeight401;
  status: 401;
};

export type updateExerciseWeightResponse404 = {
  data: UpdateExerciseWeight404;
  status: 404;
};

export type updateExerciseWeightResponse500 = {
  data: UpdateExerciseWeight500;
  status: 500;
};

export type updateExerciseWeightResponseSuccess =
  updateExerciseWeightResponse200 & {
    headers: Headers;
  };
export type updateExerciseWeightResponseError = (
  | updateExerciseWeightResponse401
  | updateExerciseWeightResponse404
  | updateExerciseWeightResponse500
) & {
  headers: Headers;
};

export type updateExerciseWeightResponse =
  | updateExerciseWeightResponseSuccess
  | updateExerciseWeightResponseError;

export const getUpdateExerciseWeightUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
) => {
  return `/${workoutPlanId}/days/${workoutDayId}/exercises/${exerciseId}/weight`;
};

export const updateExerciseWeight = async (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
  updateExerciseWeightBody: UpdateExerciseWeightBody,
  options?: RequestInit,
): Promise<updateExerciseWeightResponse> => {
  return customFetch<updateExerciseWeightResponse>(
    getUpdateExerciseWeightUrl(workoutPlanId, workoutDayId, exerciseId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateExerciseWeightBody),
    },
  );
};

/**
 * @summary Get home page data for a given date
 */
export type getHomeResponse200 = {
  data: GetHome200;
  status: 200;
};

export type getHomeResponse401 = {
  data: GetHome401;
  status: 401;
};

export type getHomeResponse404 = {
  data: GetHome404;
  status: 404;
};

export type getHomeResponse500 = {
  data: GetHome500;
  status: 500;
};

export type getHomeResponseSuccess = getHomeResponse200 & {
  headers: Headers;
};
export type getHomeResponseError = (
  | getHomeResponse401
  | getHomeResponse404
  | getHomeResponse500
) & {
  headers: Headers;
};

export type getHomeResponse = getHomeResponseSuccess | getHomeResponseError;

export const getGetHomeUrl = (date: string, params?: GetHomeParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/home/${date}?${stringifiedParams}`
    : `/home/${date}`;
};

export const getHome = async (
  date: string,
  params?: GetHomeParams,
  options?: RequestInit,
): Promise<getHomeResponse> => {
  return customFetch<getHomeResponse>(getGetHomeUrl(date, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get workout statistics for a date range
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user train data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me/`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create or update user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me/`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Create a Stripe checkout session for subscription
 */
export type postCreateCheckoutSessionResponse200 = {
  data: PostCreateCheckoutSession200;
  status: 200;
};

export type postCreateCheckoutSessionResponse401 = {
  data: PostCreateCheckoutSession401;
  status: 401;
};

export type postCreateCheckoutSessionResponse500 = {
  data: PostCreateCheckoutSession500;
  status: 500;
};

export type postCreateCheckoutSessionResponseSuccess =
  postCreateCheckoutSessionResponse200 & {
    headers: Headers;
  };
export type postCreateCheckoutSessionResponseError = (
  | postCreateCheckoutSessionResponse401
  | postCreateCheckoutSessionResponse500
) & {
  headers: Headers;
};

export type postCreateCheckoutSessionResponse =
  | postCreateCheckoutSessionResponseSuccess
  | postCreateCheckoutSessionResponseError;

export const getPostCreateCheckoutSessionUrl = () => {
  return `/create-checkout-session`;
};

export const postCreateCheckoutSession = async (
  postCreateCheckoutSessionBody: PostCreateCheckoutSessionBody,
  options?: RequestInit,
): Promise<postCreateCheckoutSessionResponse> => {
  return customFetch<postCreateCheckoutSessionResponse>(
    getPostCreateCheckoutSessionUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postCreateCheckoutSessionBody),
    },
  );
};

/**
 * @summary Get current user subscription info
 */
export type getSubscriptionResponse200 = {
  data: GetSubscription200;
  status: 200;
};

export type getSubscriptionResponse401 = {
  data: GetSubscription401;
  status: 401;
};

export type getSubscriptionResponse404 = {
  data: GetSubscription404;
  status: 404;
};

export type getSubscriptionResponse500 = {
  data: GetSubscription500;
  status: 500;
};

export type getSubscriptionResponseSuccess = getSubscriptionResponse200 & {
  headers: Headers;
};
export type getSubscriptionResponseError = (
  | getSubscriptionResponse401
  | getSubscriptionResponse404
  | getSubscriptionResponse500
) & {
  headers: Headers;
};

export type getSubscriptionResponse =
  | getSubscriptionResponseSuccess
  | getSubscriptionResponseError;

export const getGetSubscriptionUrl = () => {
  return `/subscription`;
};

export const getSubscription = async (
  options?: RequestInit,
): Promise<getSubscriptionResponse> => {
  return customFetch<getSubscriptionResponse>(getGetSubscriptionUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Cancel current subscription
 */
export type postCancelSubscriptionResponse200 = {
  data: PostCancelSubscription200;
  status: 200;
};

export type postCancelSubscriptionResponse400 = {
  data: PostCancelSubscription400;
  status: 400;
};

export type postCancelSubscriptionResponse401 = {
  data: PostCancelSubscription401;
  status: 401;
};

export type postCancelSubscriptionResponse404 = {
  data: PostCancelSubscription404;
  status: 404;
};

export type postCancelSubscriptionResponse500 = {
  data: PostCancelSubscription500;
  status: 500;
};

export type postCancelSubscriptionResponseSuccess =
  postCancelSubscriptionResponse200 & {
    headers: Headers;
  };
export type postCancelSubscriptionResponseError = (
  | postCancelSubscriptionResponse400
  | postCancelSubscriptionResponse401
  | postCancelSubscriptionResponse404
  | postCancelSubscriptionResponse500
) & {
  headers: Headers;
};

export type postCancelSubscriptionResponse =
  | postCancelSubscriptionResponseSuccess
  | postCancelSubscriptionResponseError;

export const getPostCancelSubscriptionUrl = () => {
  return `/cancel-subscription`;
};

export const postCancelSubscription = async (
  options?: RequestInit,
): Promise<postCancelSubscriptionResponse> => {
  return customFetch<postCancelSubscriptionResponse>(
    getPostCancelSubscriptionUrl(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Change subscription plan
 */
export type postChangePlanResponse200 = {
  data: PostChangePlan200;
  status: 200;
};

export type postChangePlanResponse400 = {
  data: PostChangePlan400;
  status: 400;
};

export type postChangePlanResponse401 = {
  data: PostChangePlan401;
  status: 401;
};

export type postChangePlanResponse404 = {
  data: PostChangePlan404;
  status: 404;
};

export type postChangePlanResponse500 = {
  data: PostChangePlan500;
  status: 500;
};

export type postChangePlanResponseSuccess = postChangePlanResponse200 & {
  headers: Headers;
};
export type postChangePlanResponseError = (
  | postChangePlanResponse400
  | postChangePlanResponse401
  | postChangePlanResponse404
  | postChangePlanResponse500
) & {
  headers: Headers;
};

export type postChangePlanResponse =
  | postChangePlanResponseSuccess
  | postChangePlanResponseError;

export const getPostChangePlanUrl = () => {
  return `/change-plan`;
};

export const postChangePlan = async (
  postChangePlanBody: PostChangePlanBody,
  options?: RequestInit,
): Promise<postChangePlanResponse> => {
  return customFetch<postChangePlanResponse>(getPostChangePlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postChangePlanBody),
  });
};
